sudo: false
language: java

script: ./gradlew build

jdk:
    - openjdk8
before_install:
  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew

notifications:
  slack: reportportal:fl6xWHVQp1jvsMmCJxYW9YKP